;; Lending Vault - Clarity Smart Contract Template
;; Generated by stx-clarity-toolkit

(define-data-var contract-owner principal tx-sender)
(define-data-var paused bool false)

(define-read-only (get-owner) (var-get contract-owner))
(define-read-only (is-paused) (var-get paused))

(define-public (set-paused (new-state bool))
  (begin
    (asserts! (is-eq tx-sender (var-get contract-owner)) (err u403))
    (var-set paused new-state)
    (ok true)))
